LINES = {
        'B': 'Bakerloo',
        'C': 'Central',
        'D': 'District',
        'H': 'Hammersmith & Circle',
        'J': 'Jubilee',
        'M': 'Metropolitan',
        'N': 'Northern',
        'P': 'Picadilly',
        'V': 'Victoria',
        'W': 'Waterloo & City'
        }
STATIONS = {
        'ACT': 'Acton Town.',
        'AGR': 'Arnos Grove.',
        'ALD': 'Aldgate.',
        'ALE': 'Aldgate East.',
        'ALP': 'Alperton.',
        'AME': 'Amersham.',
        'ANG': 'Angel.',
        'ARC': 'Archway.',
        'ARL': 'Arsenal.',
        'BAL': 'Balham.',
        'BAR': 'Barbican.',
        'BAY': 'Bayswater.',
        'BBB': 'Bromley-by-Bow.',
        'BCT': 'Barons Cort.',
        'BDE': 'Barkingside.',
        'BDS': 'Bond Street.',
        'BEC': 'Becontree.',
        'BER': 'Bermondsey.',
        'BGR': 'Bonds Green.',
        'BHL': 'Buckhurst Hill.',
        'BHR': 'Blackhorse Road.',
        'BKG': 'Barking.',
        'BLF': 'Blackfriars.',
        'BNG': 'Bethnal Green.',
        'BNK': 'Bank.',
        'BOR': 'Borough.',
        'BOS': 'Boston Manor.',
        'BPK': 'Belsize Park.',
        'BRX': 'Brixton.',
        'BST': 'Baker Street.',
        'BSY': 'Bushey.',
        'BTX': 'Brent Cross.',
        'BUR': 'Burnt Oak.',
        'BWR': 'Bow Road.',
        'CFS': 'Cockfosters.',
        'CHF': 'Chalk Farm.',
        'CHG': 'Chigwell.',
        'CHM': 'Chesham.',
        'CHP': 'Chiswick Park.',
        'CHX': 'Charing Cross.',
        'CLF': 'Chalfont & Latimer.',
        'CLW': 'Colliers Wood.',
        'CNT': 'Canning Town.',
        'COL': 'Colindale.',
        'COV': 'Covent Garden.',
        'CPC': 'Clapham Common.',
        'CPK': 'Canons Park.',
        'CPN': 'Clapham North.',
        'CPP': 'Carpenders Park.',
        'CPS': 'Clapham Soth.',
        'CRD': 'Caledonian Road.',
        'CRX': 'Croxley.',
        'CST': 'Cannon Street.',
        'CTN': 'Camden Town.',
        'CWD': 'Chorleywood.',
        'CWF': 'Canary Wharf.',
        'CWR': 'Canada Water.',
        'CYL': 'Chancery Lane.',
        'DEB': 'Debden.',
        'DGE': 'Dagenham East.',
        'DHL': 'Dollis Hill.',
        'EAC': 'East Acton.',
        'EBY': 'Ealing Broadway.',
        'ECM': 'Ealing Common.',
        'ECT': 'Earls Cort.',
        'EDG': 'Edgware.',
        'EFY': 'East Finchley.',
        'EHM': 'East Ham.',
        'ELE': 'Elephant & Castle.',
        'EMB': 'Embankment.',
        'EPK': 'Elm Park.',
        'EPP': 'Epping.',
        'EPY': 'East Putney.',
        'ERB': 'Edgware Road (Bakerloo).',
        'ERD': 'Edgware Road (H & C).',
        'ESQ': 'Eston Sqare.',
        'ETE': 'Eastcote.',
        'EUS': 'Euston.',
        'FAR': 'Farringdon.',
        'FBY': 'Fulham Broadway.',
        'FLP': 'Fairlop.',
        'FPK': 'Finsbry Park.',
        'FRD': 'Finchley Road.',
        'FYC': 'Finchley Central.',
        'GFD': 'Greenford.',
        'GGR': 'Golders Green.',
        'GHL': 'Gants Hill.',
        'GPK': 'Green Park.',
        'GPS': 'Great Portland Street.',
        'GRD': 'Glocester Road.',
        'GRH': 'Grange Hill.',
        'GST': 'Goodge Street.',
        'GUN': 'Gunnersbry.',
        'HAI': 'Hainault.',
        'HAT': 'Hatch End.',
        'HAW': 'Harrow & Wealdstone.',
        'HBT': 'High Barnet.',
        'HBY': 'Highbury & Islington.',
        'HCH': 'Hornchurch.',
        'HDN': 'Hillingdon.',
        'HIG': 'Highgate.',
        'HLN': 'Hanger Lane.',
        'HMD': 'Hammersmith (District and Picc).',
        'HMP': 'Hampstead.',
        'HMS': 'Hammersmith (C&H).',
        'HNC': 'Honslow Central.',
        'HND': 'Hendon Central.',
        'HNE': 'Hounslow East.',
        'HNW': 'Hounslow West.',
        'HOH': 'Harrow on the Hill.',
        'HOL': 'Holborn.',
        'HPC': 'Hyde Park Corner.',
        'HPK': 'Holland Park.',
        'HRC': 'Heathrow Terminals 123.',
        'HRD': 'Holloway Road.',
        'HRF': 'Heathrow Terminal 4.',
        'HRV': 'Heathrow Terminal 5.',
        'HSD': 'Harlesden.',
        'HSL': 'Headstone Lane.',
        'HST': 'High Street Kensington.',
        'HTX': 'Hatton Cross.',
        'ICK': 'Ickenham.',
        'KBY': 'Kingsbry.',
        'KEN': 'Kennington.',
        'KEW': 'Kew Gardens.',
        'KGN': 'Kensal Green.',
        'KIL': 'Kilburn.',
        'KNB': 'Knightsbridge.',
        'KNT': 'Kenton.',
        'KPK': 'Kilbrn Park.',
        'KTN': 'Kentish Town.',
        'KXX': "King's Cross St. Pancras.",
        'LAM': 'Lambeth North.',
        'LAN': 'Lancaster Gate.',
        'LBG': 'Ladbroke Grove.',
        'LEY': 'Leyton.',
        'LON': 'London Bridge.',
        'LSQ': 'Leicester Sqare.',
        'LST': 'Liverpool Street.',
        'LTN': 'Loughton.',
        'LYS': 'Leytonstone.',
        'MAN': 'Mansion Hose.',
        'MAR': 'Marble Arch.',
        'MCR': 'Mornington Crescent.',
        'MDV': 'Maida Vale.',
        'MGT': 'Moorgate.',
        'MHE': 'Mill Hill East.',
        'MLE': 'Mile End.',
        'MNR': 'Manor Hose.',
        'MON': 'Monument.',
        'MOR': 'Morden.',
        'MPK': 'Moor Park.',
        'MYB': 'Marylebone.',
        'NAC': 'North Acton.',
        'NEA': 'Neasden.',
        'NEL': 'North Ealing.',
        'NEP': 'Newbry Park.',
        'NFD': 'Northfields.',
        'NGW': 'North Greenwich.',
        'NHG': 'Notting Hill Gate.',
        'NHR': 'North Harrow.',
        'NHT': 'Northolt.',
        'NWD': 'Northwood.',
        'NWH': 'Northwood Hills.',
        'NWM': 'North Wembley.',
        'NWP': 'Northwick Park.',
        'OAK': 'Oakwood.',
        'OLD': 'Old Street.',
        'OLY': 'Olympia.',
        'OST': 'Osterley.',
        'OVL': 'Oval.',
        'OXC': 'Oxford Circus.',
        'PAD': 'Paddington.',
        'PER': 'Perivale.',
        'PGR': 'Parsons Green.',
        'PIC': 'Piccadilly Circs.',
        'PIM': 'Pimlico.',
        'PIN': 'Pinner.',
        'PLW': 'Plaistow.',
        'PRY': 'Park Royal.',
        'PUT': 'Putney Bridge.',
        'QBY': 'Queensbry.',
        'QPK': "Queen's Park.",
        'QWY': 'Qeensway.',
        'RCP': 'Ravenscort Park.',
        'RED': 'Redbridge.',
        'RKY': 'Rickmansworth.',
        'RLN': 'Rayners Lane.',
        'RMD': 'Richmond.',
        'ROA': 'Royal Oak.',
        'ROD': 'Roding Valley.',
        'RPK': "Regent's Park.",
        'RSQ': 'Russell Sqare.',
        'RUG': 'Ruislip Gardens.',
        'RUI': 'Ruislip.',
        'RUM': 'Ruislip Manor.',
        'SBC': 'Shepherds Bush (Central Line).',
        'SEL': 'South Ealing.',
        'SFD': 'Stratford.',
        'SFS': 'Southfields.',
        'SGT': 'Southgate.',
        'SHL': 'Sudbry Hill.',
        'SHR': 'South Harrow.',
        'SJP': "St. James's Park.",
        'SJW': "St. John's Wood.",
        'SKN': 'South Kensington.',
        'SKT': 'South Kenton.',
        'SNB': 'Snaresbrook.',
        'SPK': 'Stonebridge Park.',
        'SRP': 'South Rislip.',
        'SSQ': 'Sloane Sqare.',
        'STA': 'Stanmore.',
        'STB': 'Stamford Brook.',
        'STG': 'Stepney Green.',
        'STK': 'Stockwell.',
        'STN': 'Sudbry Town.',
        'STP': "St. Paul's.",
        'SVS': 'Seven Sisters.',
        'SWC': 'Swiss Cottage.',
        'SWF': 'South Woodford.',
        'SWK': 'Southwark.',
        'SWM': 'South Wimbledon.',
        'TBE': 'Tooting Bec.',
        'TBY': 'Tooting Broadway.',
        'TCR': 'Tottenham Court Road.',
        'TEM': 'Temple.',
        'TGR': 'Turnham Green.',
        'THB': 'Theydon Bois.',
        'THL': 'Tower Hill.',
        'TOT': 'Totteridge and Whetstone.',
        'TPK': 'Tufnell Park.',
        'TPL': 'Turnpike Lane.',
        'TTH': 'Tottenham Hale.',
        'UPB': 'Upminster Bridge.',
        'UPK': 'Upton Park.',
        'UPM': 'Upminster.',
        'UPY': 'Upney.',
        'UXB': 'Uxbridge.',
        'VIC': 'Victoria.',
        'VUX': 'Vauxhall.',
        'WAC': 'West Acton.',
        'WAL': 'Walthamstow Central.',
        'WAN': 'Wanstead.',
        'WAR': 'Warwick Avene.',
        'WAT': 'Watford.',
        'WBP': 'Westborne Park.',
        'WBT': 'West Brompton.',
        'WCL': 'Whitechapel.',
        'WCT': 'White City.',
        'WDN': 'Wimbledon.',
        'WEM': 'Wembley Central.',
        'WFD': 'Woodford.',
        'WFY': 'West Finchley.',
        'WGN': 'Wood Green.',
        'WHD': 'West Hampstead.',
        'WHM': 'West Ham.',
        'WHR': 'West Harrow.',
        'WJN': 'Willesden Junction.',
        'WKN': 'West Kensington.',
        'WLG': 'Willesden Green.',
        'WLO': 'Waterloo.',
        'WMP': 'Wimbledon Park.',
        'WMS': 'Westminster.',
        'WPK': 'Wembley Park.',
        'WRP': 'West Rislip.',
        'WSP': 'Woodside Park.',
        'WST': 'Warren Street.',
        'WTH': 'Watford High Street.',
        'WTJ': 'Watford Jnction.'
        }
LINE_STATIONS = {
        'C': ['QWY', 'WAN', 'SRP', 'EAC', 'NHT', 'EBY', 'CHG', 'HLN', 'GRH', 'SWF', 'RUG', 'WAC', 'NAC', 'RED', 'EPP', 'BDE', 'BHL', 'STP', 'LYS', 'DEB', 'WCT', 'SNB', 'MLE', 'GFD', 'CYL', 'FLP', 'MAR', 'TCR', 'BDS', 'LTN', 'ROD', 'WFD', 'BNK', 'BNG', 'NEP', 'SFD', 'OXC', 'LEY', 'HPK', 'THB', 'NHG', 'GHL', 'HOL', 'LAN', 'PER', 'WRP', 'HAI', 'SBC', 'LST'],
        'B': ['ERB', 'QPK', 'HAW', 'WEM', 'HSD', 'CPP', 'RPK', 'KPK', 'HAT', 'PIC', 'NWM', 'WAR', 'KNT', 'EMB', 'OXC', 'WLO', 'SKT', 'WJN', 'PAD', 'MYB', 'BST', 'MDV', 'KGN', 'ELE', 'LAM', 'WTH', 'CHX', 'HSL', 'BSY', 'WTJ', 'SPK'], 
        'D': ['UPM', 'PGR', 'HMD', 'BCT', 'HCH', 'CST', 'TGR', 'BLF', 'SKN', 'GRD', 'GUN', 'ACT', 'EHM', 'RCP', 'PADc', 'WDN', 'BKG', 'EPK', 'WHM', 'STG', 'PLW', 'BWR', 'ECT', 'RMD', 'MON', 'THL', 'BBB', 'OLY', 'WMP', 'VIC', 'BEC', 'EBY', 'WCL', 'HST', 'DGE', 'WBT', 'TEM', 'UPB', 'ALE', 'SJP', 'UPK', 'FBY', 'WMS', 'STB', 'ECM', 'MLE', 'WKN', 'SSQ', 'ERD', 'CHP', 'KEW', 'UPY', 'EMB', 'SFS', 'MAN', 'PUT', 'EPY'], 
        'H': ['KXX', 'FAR', 'WHM', 'RKY', 'HOH', 'ROA', 'PLW', 'BWR', 'WHR', 'GPS', 'NWH', 'BAR', 'PIN', 'WCL', 'ESQ', 'RLN', 'HST', 'CST', 'PADs', 'TEM', 'HMS', 'ALE', 'BLF', 'FRD', 'PADc', 'EHM', 'UPK', 'NHR', 'WMS', 'BKG', 'NEA', 'STG', 'SSQ', 'ERD', 'EMB', 'THL', 'MON', 'LST', 'MAN', 'VIC', 'WLG', 'BBB', 'MLE', 'LBG', 'NWD', 'BAY', 'MPK', 'NHG', 'WBP', 'BST', 'NWP', 'MGT', 'ALD', 'SKN', 'GRD', 'WPK', 'SJP'], 
        'J': ['LON', 'WLO', 'WPK', 'WLG', 'SWK', 'WMS', 'WHM', 'DHL', 'NEA', 'QBY', 'NGW', 'BST', 'CWF', 'FRD', 'BER', 'KBY', 'WHD', 'BDS', 'SWC', 'CPK', 'SJW', 'KIL', 'GPK', 'SFD', 'STA', 'CNT', 'CWR'], 
        'M': ['FRD', 'AME', 'RKY', 'CLF', 'PIN', 'ICK', 'HOH', 'RUM', 'RLN', 'CRX', 'ETE', 'CLW', 'NHR', 'MGT', 'KXX', 'UXB', 'CHM', 'HDN', 'ALD', 'WPK', 'NWH', 'BAR', 'NWP', 'ESQ', 'FAR', 'MPK', 'NWD', 'GPS', 'LST', 'RUI', 'WAT', 'BST', 'WHR', 'CWD', 'BKG'], 
        'N': ['OLD', 'OVL', 'EUS', 'LSQ', 'FYC', 'GST', 'ELE', 'KXX', 'CHF', 'HIG', 'HND', 'STK', 'MHE', 'MGT', 'LON', 'HBT', 'WLO', 'GGR', 'SWM', 'HMP', 'ARC', 'EFY', 'CPN', 'BAL', 'TOT', 'EDG', 'TBE', 'CPC', 'TCR', 'KTN', 'WST', 'TBY', 'CTN', 'CHX', 'BUR', 'MCR', 'ANG', 'CPS', 'WSP', 'EMB', 'WFY', 'CLW', 'TPK', 'KEN', 'BNK', 'BOR', 'BPK', 'COL', 'MOR', 'BTX'], 
        'P': ['NEL', 'OAK', 'COV', 'PRY', 'ETE', 'STN', 'HDN', 'FPK', 'ECT', 'ARL', 'AGR', 'ICK', 'LSQ', 'NFD', 'CRD', 'HRD', 'GRD', 'HNE', 'TPL', 'SKN', 'CFS', 'HTX', 'SHL', 'KXX', 'MNR', 'HRV', 'HNW', 'BOS', 'RSQ', 'ECM', 'SHR', 'SGT', 'RUM', 'ALP', 'OST', 'GPK', 'RUI', 'RLN', 'BCT', 'SEL', 'HNC', 'WGN', 'HRC', 'HRF', 'ACT', 'HMD', 'HPC', 'PIC', 'KNB', 'BGR', 'TGR', 'UXB', 'HOL'], 
        'W': ['WLO', 'BNK'], 
        'V': ['WST', 'VUX', 'OXC', 'GPK', 'EUS', 'STK', 'BHR', 'FPK', 'PIM', 'SVS', 'KXX', 'WAL', 'VIC', 'BRX', 'TTH', 'HBY']
        }

URLS =['http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/NEL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/OAK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/COV',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/PRY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/ETE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/STN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HDN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/FPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/ECT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/ARL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/AGR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/ICK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/LSQ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/NFD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/CRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/GRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HNE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/TPL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/SKN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/CFS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HTX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/SHL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/KXX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/MNR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HRV',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HNW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/BOS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/RSQ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/ECM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/SHR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/SGT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/RUM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/ALP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/OST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/GPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/RUI',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/RLN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/BCT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/SEL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HNC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/WGN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HRC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HRF',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/ACT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HMD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HPC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/PIC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/KNB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/BGR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/TGR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/UXB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/P/HOL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/QWY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/WAN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/SRP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/EAC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/NHT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/EBY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/CHG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/HLN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/GRH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/SWF',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/RUG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/WAC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/NAC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/RED',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/EPP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/BDE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/BHL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/STP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/LYS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/DEB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/WCT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/SNB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/MLE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/GFD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/CYL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/FLP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/MAR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/TCR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/BDS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/LTN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/ROD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/WFD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/BNK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/BNG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/NEP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/SFD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/OXC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/LEY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/HPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/THB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/NHG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/GHL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/HOL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/LAN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/PER',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/WRP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/HAI',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/SBC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/C/LST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/ERB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/QPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/HAW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/WEM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/HSD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/CPP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/RPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/KPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/HAT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/PIC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/NWM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/WAR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/KNT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/EMB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/OXC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/WLO',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/SKT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/WJN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/PAD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/MYB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/BST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/MDV',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/KGN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/ELE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/LAM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/WTH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/CHX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/HSL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/BSY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/WTJ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/B/SPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/UPM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/PGR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/HMD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/BCT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/HCH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/CST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/TGR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/BLF',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/SKN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/GRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/GUN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/ACT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/EHM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/RCP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/PADc',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/WDN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/BKG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/EPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/WHM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/STG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/PLW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/BWR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/ECT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/RMD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/MON',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/THL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/BBB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/OLY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/WMP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/VIC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/BEC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/EBY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/WCL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/HST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/DGE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/WBT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/TEM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/UPB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/ALE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/SJP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/UPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/FBY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/WMS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/STB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/ECM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/MLE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/WKN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/SSQ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/ERD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/CHP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/KEW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/UPY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/EMB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/SFS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/MAN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/PUT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/D/EPY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/W/WLO',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/W/BNK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/WST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/VUX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/OXC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/GPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/EUS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/STK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/BHR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/FPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/PIM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/SVS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/KXX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/WAL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/VIC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/BRX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/TTH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/V/HBY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/KXX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/FAR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/WHM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/RKY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/HOH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/ROA',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/PLW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/BWR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/WHR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/GPS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/NWH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/BAR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/PIN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/WCL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/ESQ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/RLN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/HST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/CST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/PADs',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/TEM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/HMS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/ALE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/BLF',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/FRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/PADc',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/EHM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/UPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/NHR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/WMS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/BKG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/NEA',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/STG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/SSQ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/ERD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/EMB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/THL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/MON',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/LST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/MAN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/VIC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/WLG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/BBB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/MLE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/LBG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/NWD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/BAY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/MPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/NHG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/WBP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/BST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/NWP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/MGT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/ALD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/SKN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/GRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/WPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/H/SJP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/LON',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/WLO',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/WPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/WLG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/SWK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/WMS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/WHM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/DHL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/NEA',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/QBY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/NGW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/BST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/CWF',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/FRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/BER',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/KBY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/WHD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/BDS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/SWC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/CPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/SJW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/KIL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/GPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/SFD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/STA',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/CNT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/J/CWR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/FRD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/AME',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/RKY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/CLF',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/PIN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/ICK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/HOH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/RUM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/RLN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/CRX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/ETE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/CLW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/NHR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/MGT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/KXX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/UXB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/CHM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/HDN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/ALD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/WPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/NWH',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/BAR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/NWP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/ESQ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/FAR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/MPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/NWD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/GPS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/LST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/RUI',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/WAT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/BST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/WHR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/CWD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/M/BKG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/OLD',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/OVL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/EUS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/LSQ',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/FYC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/GST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/ELE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/KXX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/CHF',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/HIG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/HND',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/STK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/MHE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/MGT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/LON',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/HBT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/WLO',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/GGR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/SWM',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/HMP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/ARC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/EFY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/CPN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/BAL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/TOT',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/EDG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/TBE',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/CPC',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/TCR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/KTN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/WST',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/TBY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/CTN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/CHX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/BUR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/MCR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/ANG',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/CPS',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/WSP',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/EMB',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/WFY',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/CLW',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/TPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/KEN',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/BNK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/BOR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/BPK',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/COL',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/MOR',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionDetailed/N/BTX',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/P',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/C',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/B',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/D',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/W',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/V',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/H',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/J',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/M',
 'http://cloud.tfl.gov.uk/TrackerNet/PredictionSummary/N',
 'http://cloud.tfl.gov.uk/TrackerNet/LineStatus',
 'http://cloud.tfl.gov.uk/TrackerNet/StationStatus']
 
