LINES = {
        'B': 'Bakerloo',
        'C': 'Central',
        'D': 'District',
        'H': 'Hammersmith & Circle',
        'J': 'Jubilee',
        'M': 'Metropolitan',
        'N': 'Northern',
        'P': 'Picadilly',
        'V': 'Victoria',
        'W': 'Waterloo & City'
        }
STATIONS = {
        'ACT': 'Acton Town.',
        'AGR': 'Arnos Grove.',
        'ALD': 'Aldgate.',
        'ALE': 'Aldgate East.',
        'ALP': 'Alperton.',
        'AME': 'Amersham.',
        'ANG': 'Angel.',
        'ARC': 'Archway.',
        'ARL': 'Arsenal.',
        'BAL': 'Balham.',
        'BAR': 'Barbican.',
        'BAY': 'Bayswater.',
        'BBB': 'Bromley-by-Bow.',
        'BCT': 'Barons Cort.',
        'BDE': 'Barkingside.',
        'BDS': 'Bond Street.',
        'BEC': 'Becontree.',
        'BER': 'Bermondsey.',
        'BGR': 'Bonds Green.',
        'BHL': 'Buckhurst Hill.',
        'BHR': 'Blackhorse Road.',
        'BKG': 'Barking.',
        'BLF': 'Blackfriars.',
        'BNG': 'Bethnal Green.',
        'BNK': 'Bank.',
        'BOR': 'Borough.',
        'BOS': 'Boston Manor.',
        'BPK': 'Belsize Park.',
        'BRX': 'Brixton.',
        'BST': 'Baker Street.',
        'BSY': 'Bushey.',
        'BTX': 'Brent Cross.',
        'BUR': 'Burnt Oak.',
        'BWR': 'Bow Road.',
        'CFS': 'Cockfosters.',
        'CHF': 'Chalk Farm.',
        'CHG': 'Chigwell.',
        'CHM': 'Chesham.',
        'CHP': 'Chiswick Park.',
        'CHX': 'Charing Cross.',
        'CLF': 'Chalfont & Latimer.',
        'CLW': 'Colliers Wood.',
        'CNT': 'Canning Town.',
        'COL': 'Colindale.',
        'COV': 'Covent Garden.',
        'CPC': 'Clapham Common.',
        'CPK': 'Canons Park.',
        'CPN': 'Clapham North.',
        'CPP': 'Carpenders Park.',
        'CPS': 'Clapham Soth.',
        'CRD': 'Caledonian Road.',
        'CRX': 'Croxley.',
        'CST': 'Cannon Street.',
        'CTN': 'Camden Town.',
        'CWD': 'Chorleywood.',
        'CWF': 'Canary Wharf.',
        'CWR': 'Canada Water.',
        'CYL': 'Chancery Lane.',
        'DEB': 'Debden.',
        'DGE': 'Dagenham East.',
        'DHL': 'Dollis Hill.',
        'EAC': 'East Acton.',
        'EBY': 'Ealing Broadway.',
        'ECM': 'Ealing Common.',
        'ECT': 'Earls Cort.',
        'EDG': 'Edgware.',
        'EFY': 'East Finchley.',
        'EHM': 'East Ham.',
        'ELE': 'Elephant & Castle.',
        'EMB': 'Embankment.',
        'EPK': 'Elm Park.',
        'EPP': 'Epping.',
        'EPY': 'East Putney.',
        'ERB': 'Edgware Road (Bakerloo).',
        'ERD': 'Edgware Road (H & C).',
        'ESQ': 'Eston Sqare.',
        'ETE': 'Eastcote.',
        'EUS': 'Euston.',
        'FAR': 'Farringdon.',
        'FBY': 'Fulham Broadway.',
        'FLP': 'Fairlop.',
        'FPK': 'Finsbry Park.',
        'FRD': 'Finchley Road.',
        'FYC': 'Finchley Central.',
        'GFD': 'Greenford.',
        'GGR': 'Golders Green.',
        'GHL': 'Gants Hill.',
        'GPK': 'Green Park.',
        'GPS': 'Great Portland Street.',
        'GRD': 'Glocester Road.',
        'GRH': 'Grange Hill.',
        'GST': 'Goodge Street.',
        'GUN': 'Gunnersbry.',
        'HAI': 'Hainault.',
        'HAT': 'Hatch End.',
        'HAW': 'Harrow & Wealdstone.',
        'HBT': 'High Barnet.',
        'HBY': 'Highbury & Islington.',
        'HCH': 'Hornchurch.',
        'HDN': 'Hillingdon.',
        'HIG': 'Highgate.',
        'HLN': 'Hanger Lane.',
        'HMD': 'Hammersmith (District and Picc).',
        'HMP': 'Hampstead.',
        'HMS': 'Hammersmith (C&H).',
        'HNC': 'Honslow Central.',
        'HND': 'Hendon Central.',
        'HNE': 'Hounslow East.',
        'HNW': 'Hounslow West.',
        'HOH': 'Harrow on the Hill.',
        'HOL': 'Holborn.',
        'HPC': 'Hyde Park Corner.',
        'HPK': 'Holland Park.',
        'HRC': 'Heathrow Terminals 123.',
        'HRD': 'Holloway Road.',
        'HRF': 'Heathrow Terminal 4.',
        'HRV': 'Heathrow Terminal 5.',
        'HSD': 'Harlesden.',
        'HSL': 'Headstone Lane.',
        'HST': 'High Street Kensington.',
        'HTX': 'Hatton Cross.',
        'ICK': 'Ickenham.',
        'KBY': 'Kingsbry.',
        'KEN': 'Kennington.',
        'KEW': 'Kew Gardens.',
        'KGN': 'Kensal Green.',
        'KIL': 'Kilburn.',
        'KNB': 'Knightsbridge.',
        'KNT': 'Kenton.',
        'KPK': 'Kilbrn Park.',
        'KTN': 'Kentish Town.',
        'KXX': "King's Cross St. Pancras.",
        'LAM': 'Lambeth North.',
        'LAN': 'Lancaster Gate.',
        'LBG': 'Ladbroke Grove.',
        'LEY': 'Leyton.',
        'LON': 'London Bridge.',
        'LSQ': 'Leicester Sqare.',
        'LST': 'Liverpool Street.',
        'LTN': 'Loughton.',
        'LYS': 'Leytonstone.',
        'MAN': 'Mansion Hose.',
        'MAR': 'Marble Arch.',
        'MCR': 'Mornington Crescent.',
        'MDV': 'Maida Vale.',
        'MGT': 'Moorgate.',
        'MHE': 'Mill Hill East.',
        'MLE': 'Mile End.',
        'MNR': 'Manor Hose.',
        'MON': 'Monument.',
        'MOR': 'Morden.',
        'MPK': 'Moor Park.',
        'MYB': 'Marylebone.',
        'NAC': 'North Acton.',
        'NEA': 'Neasden.',
        'NEL': 'North Ealing.',
        'NEP': 'Newbry Park.',
        'NFD': 'Northfields.',
        'NGW': 'North Greenwich.',
        'NHG': 'Notting Hill Gate.',
        'NHR': 'North Harrow.',
        'NHT': 'Northolt.',
        'NWD': 'Northwood.',
        'NWH': 'Northwood Hills.',
        'NWM': 'North Wembley.',
        'NWP': 'Northwick Park.',
        'OAK': 'Oakwood.',
        'OLD': 'Old Street.',
        'OLY': 'Olympia.',
        'OST': 'Osterley.',
        'OVL': 'Oval.',
        'OXC': 'Oxford Circus.',
        'PAD': 'Paddington.',
        'PER': 'Perivale.',
        'PGR': 'Parsons Green.',
        'PIC': 'Piccadilly Circs.',
        'PIM': 'Pimlico.',
        'PIN': 'Pinner.',
        'PLW': 'Plaistow.',
        'PRY': 'Park Royal.',
        'PUT': 'Putney Bridge.',
        'QBY': 'Queensbry.',
        'QPK': "Queen's Park.",
        'QWY': 'Qeensway.',
        'RCP': 'Ravenscort Park.',
        'RED': 'Redbridge.',
        'RKY': 'Rickmansworth.',
        'RLN': 'Rayners Lane.',
        'RMD': 'Richmond.',
        'ROA': 'Royal Oak.',
        'ROD': 'Roding Valley.',
        'RPK': "Regent's Park.",
        'RSQ': 'Russell Sqare.',
        'RUG': 'Ruislip Gardens.',
        'RUI': 'Ruislip.',
        'RUM': 'Ruislip Manor.',
        'SBC': 'Shepherds Bush (Central Line).',
        'SEL': 'South Ealing.',
        'SFD': 'Stratford.',
        'SFS': 'Southfields.',
        'SGT': 'Southgate.',
        'SHL': 'Sudbry Hill.',
        'SHR': 'South Harrow.',
        'SJP': "St. James's Park.",
        'SJW': "St. John's Wood.",
        'SKN': 'South Kensington.',
        'SKT': 'South Kenton.',
        'SNB': 'Snaresbrook.',
        'SPK': 'Stonebridge Park.',
        'SRP': 'South Rislip.',
        'SSQ': 'Sloane Sqare.',
        'STA': 'Stanmore.',
        'STB': 'Stamford Brook.',
        'STG': 'Stepney Green.',
        'STK': 'Stockwell.',
        'STN': 'Sudbry Town.',
        'STP': "St. Paul's.",
        'SVS': 'Seven Sisters.',
        'SWC': 'Swiss Cottage.',
        'SWF': 'South Woodford.',
        'SWK': 'Southwark.',
        'SWM': 'South Wimbledon.',
        'TBE': 'Tooting Bec.',
        'TBY': 'Tooting Broadway.',
        'TCR': 'Tottenham Court Road.',
        'TEM': 'Temple.',
        'TGR': 'Turnham Green.',
        'THB': 'Theydon Bois.',
        'THL': 'Tower Hill.',
        'TOT': 'Totteridge and Whetstone.',
        'TPK': 'Tufnell Park.',
        'TPL': 'Turnpike Lane.',
        'TTH': 'Tottenham Hale.',
        'UPB': 'Upminster Bridge.',
        'UPK': 'Upton Park.',
        'UPM': 'Upminster.',
        'UPY': 'Upney.',
        'UXB': 'Uxbridge.',
        'VIC': 'Victoria.',
        'VUX': 'Vauxhall.',
        'WAC': 'West Acton.',
        'WAL': 'Walthamstow Central.',
        'WAN': 'Wanstead.',
        'WAR': 'Warwick Avene.',
        'WAT': 'Watford.',
        'WBP': 'Westborne Park.',
        'WBT': 'West Brompton.',
        'WCL': 'Whitechapel.',
        'WCT': 'White City.',
        'WDN': 'Wimbledon.',
        'WEM': 'Wembley Central.',
        'WFD': 'Woodford.',
        'WFY': 'West Finchley.',
        'WGN': 'Wood Green.',
        'WHD': 'West Hampstead.',
        'WHM': 'West Ham.',
        'WHR': 'West Harrow.',
        'WJN': 'Willesden Junction.',
        'WKN': 'West Kensington.',
        'WLG': 'Willesden Green.',
        'WLO': 'Waterloo.',
        'WMP': 'Wimbledon Park.',
        'WMS': 'Westminster.',
        'WPK': 'Wembley Park.',
        'WRP': 'West Rislip.',
        'WSP': 'Woodside Park.',
        'WST': 'Warren Street.',
        'WTH': 'Watford High Street.',
        'WTJ': 'Watford Jnction.'
        }
LINE_STATIONS = {
        'C': ['QWY', 'WAN', 'SRP', 'EAC', 'NHT', 'EBY', 'CHG', 'HLN', 'GRH', 'SWF', 'RUG', 'WAC', 'NAC', 'RED', 'EPP', 'BDE', 'BHL', 'STP', 'LYS', 'DEB', 'WCT', 'SNB', 'MLE', 'GFD', 'CYL', 'FLP', 'MAR', 'TCR', 'BDS', 'LTN', 'ROD', 'WFD', 'BNK', 'BNG', 'NEP', 'SFD', 'OXC', 'LEY', 'HPK', 'THB', 'NHG', 'GHL', 'HOL', 'LAN', 'PER', 'WRP', 'HAI', 'SBC', 'LST'],
        'B': ['ERB', 'QPK', 'HAW', 'WEM', 'HSD', 'CPP', 'RPK', 'KPK', 'HAT', 'PIC', 'NWM', 'WAR', 'KNT', 'EMB', 'OXC', 'WLO', 'SKT', 'WJN', 'PAD', 'MYB', 'BST', 'MDV', 'KGN', 'ELE', 'LAM', 'WTH', 'CHX', 'HSL', 'BSY', 'WTJ', 'SPK'], 
        'D': ['UPM', 'PGR', 'HMD', 'BCT', 'HCH', 'CST', 'TGR', 'BLF', 'SKN', 'GRD', 'GUN', 'ACT', 'EHM', 'RCP', 'PADc', 'WDN', 'BKG', 'EPK', 'WHM', 'STG', 'PLW', 'BWR', 'ECT', 'RMD', 'MON', 'THL', 'BBB', 'OLY', 'WMP', 'VIC', 'BEC', 'EBY', 'WCL', 'HST', 'DGE', 'WBT', 'TEM', 'UPB', 'ALE', 'SJP', 'UPK', 'FBY', 'WMS', 'STB', 'ECM', 'MLE', 'WKN', 'SSQ', 'ERD', 'CHP', 'KEW', 'UPY', 'EMB', 'SFS', 'MAN', 'PUT', 'EPY'], 
        'H': ['KXX', 'FAR', 'WHM', 'RKY', 'HOH', 'ROA', 'PLW', 'BWR', 'WHR', 'GPS', 'NWH', 'BAR', 'PIN', 'WCL', 'ESQ', 'RLN', 'HST', 'CST', 'PADs', 'TEM', 'HMS', 'ALE', 'BLF', 'FRD', 'PADc', 'EHM', 'UPK', 'NHR', 'WMS', 'BKG', 'NEA', 'STG', 'SSQ', 'ERD', 'EMB', 'THL', 'MON', 'LST', 'MAN', 'VIC', 'WLG', 'BBB', 'MLE', 'LBG', 'NWD', 'BAY', 'MPK', 'NHG', 'WBP', 'BST', 'NWP', 'MGT', 'ALD', 'SKN', 'GRD', 'WPK', 'SJP'], 
        'J': ['LON', 'WLO', 'WPK', 'WLG', 'SWK', 'WMS', 'WHM', 'DHL', 'NEA', 'QBY', 'NGW', 'BST', 'CWF', 'FRD', 'BER', 'KBY', 'WHD', 'BDS', 'SWC', 'CPK', 'SJW', 'KIL', 'GPK', 'SFD', 'STA', 'CNT', 'CWR'], 
        'M': ['FRD', 'AME', 'RKY', 'CLF', 'PIN', 'ICK', 'HOH', 'RUM', 'RLN', 'CRX', 'ETE', 'CLW', 'NHR', 'MGT', 'KXX', 'UXB', 'CHM', 'HDN', 'ALD', 'WPK', 'NWH', 'BAR', 'NWP', 'ESQ', 'FAR', 'MPK', 'NWD', 'GPS', 'LST', 'RUI', 'WAT', 'BST', 'WHR', 'CWD', 'BKG'], 
        'N': ['OLD', 'OVL', 'EUS', 'LSQ', 'FYC', 'GST', 'ELE', 'KXX', 'CHF', 'HIG', 'HND', 'STK', 'MHE', 'MGT', 'LON', 'HBT', 'WLO', 'GGR', 'SWM', 'HMP', 'ARC', 'EFY', 'CPN', 'BAL', 'TOT', 'EDG', 'TBE', 'CPC', 'TCR', 'KTN', 'WST', 'TBY', 'CTN', 'CHX', 'BUR', 'MCR', 'ANG', 'CPS', 'WSP', 'EMB', 'WFY', 'CLW', 'TPK', 'KEN', 'BNK', 'BOR', 'BPK', 'COL', 'MOR', 'BTX'], 
        'P': ['NEL', 'OAK', 'COV', 'PRY', 'ETE', 'STN', 'HDN', 'FPK', 'ECT', 'ARL', 'AGR', 'ICK', 'LSQ', 'NFD', 'CRD', 'HRD', 'GRD', 'HNE', 'TPL', 'SKN', 'CFS', 'HTX', 'SHL', 'KXX', 'MNR', 'HRV', 'HNW', 'BOS', 'RSQ', 'ECM', 'SHR', 'SGT', 'RUM', 'ALP', 'OST', 'GPK', 'RUI', 'RLN', 'BCT', 'SEL', 'HNC', 'WGN', 'HRC', 'HRF', 'ACT', 'HMD', 'HPC', 'PIC', 'KNB', 'BGR', 'TGR', 'UXB', 'HOL'], 
        'W': ['WLO', 'BNK'], 
        'V': ['WST', 'VUX', 'OXC', 'GPK', 'EUS', 'STK', 'BHR', 'FPK', 'PIM', 'SVS', 'KXX', 'WAL', 'VIC', 'BRX', 'TTH', 'HBY']
        }

